services:
  dotnetmonitor:
    image: mcr.microsoft.com/dotnet/monitor:10.0.0
    user: root
    ports:
      - 127.0.0.1:52323:52323
      - 127.0.0.1:52325:52325
    environment:
      - DOTNETMONITOR_DiagnosticPort__ConnectionMode=Listen
      - DOTNETMONITOR_Storage__DefaultSharedPath=/diag
      - DOTNETMONITOR_Urls=http://+:52323
      - DOTNETMONITOR_Metrics__Endpoints=http://+:52325
      - DotnetMonitor_InProcessFeatures__Enabled=true
      - DotnetMonitor_InProcessFeatures__CallStacks__Enabled=true
      - DotnetMonitor_InProcessFeatures__Exceptions__Enabled=true
    volumes:
      - dotnet-monitor-data:/diag
    command:
      - collect
      - --no-auth

  otel-collector:
    image: "otel/opentelemetry-collector-contrib:latest"
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
      - ./collector-logs:/var/otel-logs
    ports:
      - 127.0.0.1:4317:4317
      - 127.0.0.1:4318:4318
      - 127.0.0.1:8889:8889
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:v3.5.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --storage.tsdb.retention.time=1y
      - --storage.tsdb.retention.size=1GB
      - --web.enable-otlp-receiver
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  dotnet-monitor-data:
  prometheus-data:
